name: mtpy-v2-test
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numpy=1.26
  - git
  - pip
  - simpeg
  - dill
  - jupyterlab
  - ipywidgets
  - mkl-devel
  - pkg-config
  - cmake
  - cython 
  - ninja
  - xarray=2024.7.0
