name: mtpy-v2-test
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - xarray
  - matplotlib
  - pyproj
  - configparser
  - geopandas
  - rasterio
  - contextily
  - pyevtk
  - simpeg
  - dill
  - git
  - pip
  - jupyterlab
  - ipywidgets
  - mkl-devel
  - pkg-config
  - cmake
  - cython 
  - ninja
  - pip:
      - mt_metadata[obspy]>=1.0.0
      - mth5>=0.6.0
      - aurora
