name: mtpy-v2-test
channels:
  - conda-forge
dependencies:
  - python=3.11
  - git
  - pip
  - matplotlib
  - numpy=1.26
  - scipy
  - pyproj
  - configparser
  - geopandas
  - pyevtk
  - rasterio
  - contextily
  - mt-metadata
  - mth5
  - simpeg>=0.22
  - mkl-devel
  - pkg-config
  - cmake
  - cython 
  - ninja
  - aurora

