name: mtpy-v2-test
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - matplotlib
  - numpy
  - git
  - pip
  - simpeg
  - dill
  - jupyterlab
  - ipywidgets
  - mkl-devel
  - pkg-config
  - cmake
  - cython 
  - ninja
